title: Dinosaur decisions
hero_image: images/banner.png
description: Create a paper based decision tree to classify dinosaurs, and learn how machine learning models use decision trees to classify data.
version: 1
listed: false
copyedit: false
last_tested: "2024-06-27"
steps:
  - title: Introduction
  - title: Classify some data
  - title: What next?
