title: Dinosaur decision tree
hero_image: images/banner.png
description: Create a paper-based decision tree to classify dinosaurs, and learn how machine learning models use decision trees to classify data
version: 1
listed: true
copyedit: false
last_tested: "2024-06-27"
steps:
  - 
    title: भूमिका
  - 
    title: Classify the dinosaurs
    completion:
      - engaged
  - 
    title: Modify the criteria
  - 
    title: More than one question
    completion:
      - internal
  - 
    title: Decision tree
    challenge: true
  - 
    title: आगे क्या?
    completion:
      - external
