---
title: Δέντρο αποφάσεων δεινοσαύρων
hero_image: images/banner.png
description: Δημιούργησε ένα δέντρο αποφάσεων σε χαρτί για να ταξινομήσεις τους δεινόσαυρους και μάθε πώς τα μοντέλα μηχανικής μάθησης χρησιμοποιούν δέντρα αποφάσεων για την ταξινόμηση δεδομένων
version: 1
listed: true
copyedit: false
last_tested: "2024-06-27"
steps:
  - title: Τι θα φτιάξεις
  - title: Ταξινόμησε τους δεινόσαυρους
    completion:
      - engaged
  - title: Τροποποίηση των κριτηρίων
  - title: Περισσότερες από μία ερωτήσεις
    completion:
      - internal
  - title: Δέντρο αποφάσεων
    challenge: true
    completion:
      - external
