---
title: Albero decisionale dei dinosauri
hero_image: images/banner.png
description: Crea un albero decisionale cartaceo per classificare i dinosauri e scopri come i modelli di apprendimento automatico utilizzano gli alberi decisionale per classificare i dati
version: 1
listed: true
copyedit: false
last_tested: "2024-06-27"
steps:
  - title: Cosa creerai
  - title: Classifica i dinosauri
    completion:
    - engaged
  - title: Modifica i criteri
  - title: Più di una domanda
    completion:
    - internal
  - title: Albero decisionale
    challenge: true
    completion:
    - external